// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJobRun = "job_run"

// JobRun mapped from table <job_run>
type JobRun struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP not null" json:"created_at"`
	JobID       string    `gorm:"column:job_id" json:"job_id"`
	Results     int64     `gorm:"column:results" json:"results"`
	Description string    `gorm:"column:description" json:"description"`
	CompletedAt time.Time `gorm:"column:completed_at" json:"completed_at"`
	ModelID     int32     `gorm:"column:model_id" json:"model_id"`
}

// TableName JobRun's table name
func (*JobRun) TableName() string {
	return TableNameJobRun
}
