// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameJobSource = "job_source"

// JobSource mapped from table <job_source>
type JobSource struct {
	ID   int32  `gorm:"column:id;primaryKey" json:"id"`
	Name string `gorm:"column:name" json:"name"`
}

// TableName JobSource's table name
func (*JobSource) TableName() string {
	return TableNameJobSource
}
