// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMake = "make"

// Make mapped from table <make>
type Make struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	OldID       int32     `gorm:"column:old_id;type:INTEGER" json:"old_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Location    string    `gorm:"column:location" json:"location"`
	Description string    `gorm:"column:description" json:"description"`
	Nationality string    `gorm:"column:nationality" json:"nationality"`
	Slug        string    `gorm:"column:slug;not null" json:"slug"`
	Created     time.Time `gorm:"column:created" json:"created"`
	URL         string    `gorm:"column:url" json:"url"`
	Active      int32     `gorm:"column:active" json:"active"`
}

// TableName Make's table name
func (*Make) TableName() string {
	return TableNameMake
}
