// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameModel = "model"

// Model mapped from table <model>
type Model struct {
	ID      int32     `gorm:"column:id;primaryKey" json:"id"`
	Name    string    `gorm:"column:name;not null" json:"name"`
	Slug    string    `gorm:"column:slug;not null" json:"slug"`
	Details string    `gorm:"column:details" json:"details"`
	MakeID  int32     `gorm:"column:make_id;type:INTEGER" json:"make_id"`
	Created time.Time `gorm:"column:created" json:"created"`
	Active  int32     `gorm:"column:active" json:"active"`
}

// TableName Model's table name
func (*Model) TableName() string {
	return TableNameModel
}
