// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameModelSourceMapping = "model_source_mapping"

// ModelSourceMapping mapped from table <model_source_mapping>
type ModelSourceMapping struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP not null" json:"created_at"`
	ModelID     int32     `gorm:"column:model_id;type:INTEGER" json:"model_id"`
	Make        string    `gorm:"column:make" json:"make"`
	Model       string    `gorm:"column:model" json:"model"`
	JobSourceID int64     `gorm:"column:job_source_id;type:bigint" json:"job_source_id"`
}

// TableName ModelSourceMapping's table name
func (*ModelSourceMapping) TableName() string {
	return TableNameModelSourceMapping
}
